name: infinity
channels:
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - binutils_impl_linux-64=2.44=hdf8817f_2
  - binutils_linux-64=2.44=h4852527_2
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - cuda-cccl_linux-64=12.6.77=0
  - cuda-command-line-tools=12.6.3=0
  - cuda-compiler=12.6.3=0
  - cuda-crt-dev_linux-64=12.6.85=0
  - cuda-crt-tools=12.6.85=0
  - cuda-cudart=12.6.77=0
  - cuda-cudart-dev=12.6.77=0
  - cuda-cudart-dev_linux-64=12.6.77=0
  - cuda-cudart-static=12.6.77=0
  - cuda-cudart-static_linux-64=12.6.77=0
  - cuda-cudart_linux-64=12.6.77=0
  - cuda-cuobjdump=12.6.77=0
  - cuda-cupti=12.6.80=0
  - cuda-cupti-dev=12.6.80=0
  - cuda-cuxxfilt=12.6.77=0
  - cuda-driver-dev=12.6.77=0
  - cuda-driver-dev_linux-64=12.6.77=0
  - cuda-gdb=12.6.77=0
  - cuda-libraries=12.6.3=0
  - cuda-libraries-dev=12.6.3=0
  - cuda-nsight=12.6.77=0
  - cuda-nvcc=12.6.85=0
  - cuda-nvcc-dev_linux-64=12.6.85=0
  - cuda-nvcc-impl=12.6.85=0
  - cuda-nvcc-tools=12.6.85=0
  - cuda-nvcc_linux-64=12.6.85=0
  - cuda-nvdisasm=12.6.77=0
  - cuda-nvml-dev=12.6.77=2
  - cuda-nvprof=12.6.80=0
  - cuda-nvprune=12.6.77=0
  - cuda-nvrtc=12.6.85=0
  - cuda-nvrtc-dev=12.6.85=0
  - cuda-nvtx=12.6.77=0
  - cuda-nvvm-dev_linux-64=12.6.85=0
  - cuda-nvvm-impl=12.6.85=0
  - cuda-nvvm-tools=12.6.85=0
  - cuda-nvvp=12.6.80=0
  - cuda-opencl=12.6.77=0
  - cuda-opencl-dev=12.6.77=0
  - cuda-profiler-api=12.6.77=0
  - cuda-sanitizer-api=12.6.77=0
  - cuda-toolkit=12.6.3=0
  - cuda-tools=12.6.3=0
  - cuda-version=12.6=3
  - cuda-visual-tools=12.6.3=0
  - dbus=1.16.2=h3c4dab8_0
  - debugpy=1.8.17=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=hecca717_0
  - fontconfig=2.15.0=h7e30c49_1
  - freetype=2.14.1=ha770c72_0
  - gcc_impl_linux-64=12.4.0=h26ba24d_2
  - gcc_linux-64=12.4.0=h6b7512a_10
  - gds-tools=1.11.1.6=0
  - gmp=6.3.0=hac33072_2
  - gxx_impl_linux-64=12.4.0=h3ff227c_2
  - gxx_linux-64=12.4.0=h8489865_10
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.0.1=pyha191276_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=ha97dd6f_2
  - libcublas=12.6.4.1=0
  - libcublas-dev=12.6.4.1=0
  - libcufft=11.3.0.4=0
  - libcufft-dev=11.3.0.4=0
  - libcufile=1.11.1.6=0
  - libcufile-dev=1.11.1.6=0
  - libcurand=10.3.7.77=0
  - libcurand-dev=10.3.7.77=0
  - libcusolver=11.7.1.2=0
  - libcusolver-dev=11.7.1.2=0
  - libcusparse=12.5.4.2=0
  - libcusparse-dev=12.5.4.2=0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=12.4.0=h1762d19_102
  - libgcc-ng=15.2.0=h69a702a_7
  - libglib=2.86.0=h32235b2_1
  - libgomp=15.2.0=h767d61c_7
  - libiconv=1.18=h3b78370_2
  - liblzma=5.8.1=hb9d3cd8_2
  - libnpp=12.2.5.30=0
  - libnpp-dev=12.2.5.30=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvfatbin=12.6.77=0
  - libnvfatbin-dev=12.6.77=0
  - libnvjitlink=12.6.85=0
  - libnvjitlink-dev=12.6.85=0
  - libnvjpeg=12.3.1.117=0
  - libnvjpeg-dev=12.3.1.117=0
  - libpng=1.6.50=h421ea60_1
  - libsanitizer=12.4.0=ha732cd4_2
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=12.4.0=h1762d19_102
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.12.2=hca5e8e5_0
  - libxml2=2.15.1=h031cc0b_0
  - libxml2-16=2.15.1=hf2a90c1_0
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nsight-compute=2024.3.2.3=0
  - nspr=4.37=h29cc59b_0
  - nss=3.117=h445c969_0
  - openssl=3.5.4=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h1321c63_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py310h7c4b9e2_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.19=hd994cfb_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyzmq=27.1.0=py310h4f33d48_0
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sysroot_linux-64=2.34=h087de78_2
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py310h7c4b9e2_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - args==0.1.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - braceexpand==0.1.7
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.3.0
      - clint==0.5.1
      - clip-benchmark==1.6.2
      - cmake==4.1.2
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - decord==0.6.0
      - diffusers==0.35.2
      - distro==1.9.0
      - docstring-parser==0.17.0
      - easydict==1.13
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - filelock==3.19.1
      - flash-attn==2.8.3
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gputil==1.4.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - hpsv2==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.11
      - imageio==2.37.0
      - iniconfig==2.3.0
      - jinja2==3.1.6
      - jiter==0.11.1
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lightning-utilities==0.15.2
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mmdet==3.3.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - networkx==3.3
      - ninja==1.13.0
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py3==7.352.0
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - open-clip-torch==3.2.0
      - openai==2.6.1
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - pandas==2.3.3
      - pillow==11.3.0
      - pip==25.3
      - pluggy==1.6.0
      - propcache==0.4.1
      - protobuf==3.20.3
      - pyarrow==22.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.10
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pyparsing==3.2.5
      - pytest==7.2.0
      - pytest-split==0.8.0
      - pytorch-fid==0.3.0
      - pytorch-lightning==2.5.5
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.9.18
      - requests==2.32.5
      - rfc3986==1.5.0
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - sentry-sdk==2.42.0
      - shapely==2.1.2
      - smmap==5.0.2
      - sniffio==1.3.1
      - sympy==1.14.0
      - terminaltables==3.1.10
      - threadpoolctl==3.6.0
      - timm==1.0.20
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.9.0+cu126
      - torchmetrics==1.8.2
      - torchvision==0.24.0+cu126
      - tqdm==4.67.1
      - transformers==4.57.1
      - triton==3.5.0
      - typed-argument-parser==1.11.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.22.2
      - webdataset==1.0.2
      - yarl==1.22.0
